### ISSUE TITLE
Global test types overrides causing typescript issues

### ISSUE THREAD

**Issue by fredrik-j-lindberg** [crutchcorn/cli-testing-library#38]
- `cli-testing-library` version: 3.0.1
- Testing Framework and version: vitest@3.1.1

### Relevant code or config:

```js
  ...
  afterEach(() => {
  ...
```

### What you did:

Ran type checking after upgrading to 3.0.1

### What happened:

The afterEach cause the following issue:

`error TS2722: Cannot invoke an object which is possibly 'undefined'.`

### Reproduction:

1. Install and setup typescript, vitest and latest version of this lib
2. Have a test with an afterEach
3. Run type checking

For an easier time debugging it, make sure `skipLibCheck` is false as that shows the type conflicts that causes this issue.

If necessary I can provide a reproduction but avoiding it for now since it is hopefully decently self-explanatory

### Problem description:

The new version of the lib has a global overwrite of the afterEach (and other) types [here](https://github.com/crutchcorn/cli-testing-library/blob/main/packages/cli-testing-library/src/types.ts#L13), introduced in [this PR](https://github.com/crutchcorn/cli-testing-library/pull/31/files).

### Suggested solution:

Not overriding the global test types. We have removed them in a patch on our end to get around this issue atm.
